config/routes.rb
Rails.application.routes.draw do

  resources :resumes
	root 'welcome#index'

	get '/', to: 'welcome#new'
	post '/', to: 'welcome#create'
  
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

	resources :blogs
	resources :categories
	resources :works
	resources :photos
		

end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :category
	
	has_many :photos, :dependent => :destroy
	accepts_nested_attributes_for :photos, reject_if: proc { |attributes| attributes['title'].blank? }, :allow_destroy => true

	validates :title, :description, :year, :presence => true
end

app/controllers/works_controller.rb
class WorksController < InheritedResources::Base
	before_filter :basic_authenticate
	before_action :set_work, only: [:show, :edit, :update, :destroy]

	# GET /works
	# GET /works.json
	def index
		@works = Work.all
	end

	# GET /works/1
	# GET /works/1.json
	def show
		@categories = @work.category.name
	end

	# GET /works/new
	def new
		@work = Work.new
		@categories = Category.all.map{ |c| [ c.name, c.id ] }
	end

	# POST /works
	# POST /works.json
	def create
		@work = Work.new(work_params)
		# @work.category_id = params[:category_id]

		respond_to do |format|
			if @work.save
				format.html { redirect_to @work, notice: 'work was successfully created.' }
				format.json { render :show, status: :created, location: @work }
			else
				format.html { render :new }
				format.json { render json: @work.errors, status: :unprocessable_entity }
			end
		end
	end

	# GET /works/1/edit
	def edit
		@categories = Category.all.map{ |c| [ c.name, c.id ] }
	end

	# PATCH/PUT /works/1
	# PATCH/PUT /works/1.json
	def update
	@work.category_id = params[:category_id]
		respond_to do |format|
			if @work.update(work_params)
				format.html { redirect_to @work, notice: 'work was successfully updated.' }
				format.json { render :show, status: :ok, location: @work }
			else
				format.html { render :edit }
				format.json { render json: @work.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /works/1
	# DELETE /works/1.json
	def destroy
		@work.destroy
		respond_to do |format|
			format.html { redirect_to works_url, notice: 'work was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_work
			@work = Work.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def work_params
			params.require(:work).permit(:id, :title, :description, :year, :place, :category_id, 
				photos_attributes: [:id, :title, :image, :_destroy])
		end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= simple_form_for @work, html: { :multipart => true } do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :year, collection: 2007..Date.today.year, prompt: "Select year" %>
	<%= f.input :place %>
	<%= f.input :category_id, collection: @categories, prompt: "Please select" %>
	<h3 id="photos">Photos</h3>
	<%= f.simple_fields_for :photos do |photo| %>
		<%= render 'photo_fields', :f => photo %>
	<% end %>
	<div class="links">
		<%= link_to_add_association 'add photo', f, :photos %>
	</div>
	<br>
	<div class="actions">
		<%= f.button :submit, 'Save Work', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
	</div>
<% end %>

app/views/works/_photo_fields.html.erb
  <%= f.input :title %>
  <%= f.input :image %>
  <%= link_to_remove_association "remove photo", f %> <!-- werkt wel maar niet zichtbaar -->

app/views/works/edit.html.erb
<div class="container">

<h1>Editing Work</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

</div>

app/views/works/index.html.erb
<div class="container">
<p id="notice" class="text-success"><%= notice %></p>

<h1>Listing Works</h1>

<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Year</th>
			<th>Category</th>
			<th>Number of photos</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @works.each do |work| %>
			<tr>
				<td><%= work.title %></td>
				<td><%= work.description %></td>
				<td><%= work.year %></td>
				<td><%= work.category.name %></td>
				<td><%= work.photos.count %></td> 
				<td><%= link_to 'Show', work %></td>
				<td><%= link_to 'Edit', edit_work_path(work) %></td>
				<td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>
</div>

app/views/works/new.html.erb
<div class="container">
<h1>New Work</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', works_path %>
</div>

app/views/works/show.html.erb
<div class="container">
<p id="notice" class="text-success"><%= notice %></p>

<h3><%= @work.title %></h3>

<p>
	<strong>Description:</strong>
	<%= @work.description %>
</p>

<p>
	<strong>Year:</strong>
	<%= @work.year %>
</p>

<p>
	<strong>Place:</strong>
	<%= @work.place %>
</p>

<p>
	<strong>Category:</strong>
	<%= @work.category.name %>
</p>

<p>
	<strong>Photo(s):</strong><br>
	<% for photo in @work.photos %>
		<%= photo.title %><br>
		<%= image_tag photo.image.url(:medium) %><br>
	<% end %>
</p>

<br>
<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>
</div>