config/routes.rb
Rails.application.routes.draw do

  resources :resumes
	root 'welcome#index'

	get '/', to: 'welcome#new'
	post '/', to: 'welcome#create'
  
	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

	resources :blogs
	resources :categories
	resources :works
	resources :photos
		

end

app/models/resume.rb
class Resume < ActiveRecord::Base
	validates :title, :year, presence: :true
end

app/controllers/resumes_controller.rb
class ResumesController < InheritedResources::Base
	before_filter :basic_authenticate, only: [:new, :create, :destroy]

  private

    def resume_params
      params.require(:resume).permit(:title, :year, :location, :text, :artists, :curator, :link)
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= simple_form_for(@resume) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :year, collection: 2007..Date.today.year, prompt: "Select year" %>
    <%= f.input :location %>
    <%= f.input :text %>
    <%= f.input :artists %>
    <%= f.input :curator %>
    <%= f.input :link %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Listing Resumes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Location</th>
      <th>Text</th>
      <th>Artists</th>
      <th>Curator</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.title %></td>
        <td><%= resume.year %></td>
        <td><%= resume.location %></td>
        <td><%= resume.text %></td>
        <td><%= resume.artists %></td>
        <td><%= resume.curator %></td>
        <td><%= resume.link %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Resume', new_resume_path %>

</div>

app/views/resumes/new.html.erb
<div class="container">
<h1>New Resume</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', resumes_path %>
</div>

app/views/resumes/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resume.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @resume.year %>
</p>

<p>
  <strong>Location:</strong>
  <%= @resume.location %>
</p>

<p>
  <strong>Text:</strong>
  <%= @resume.text %>
</p>

<p>
  <strong>Artists:</strong>
  <%= @resume.artists %>
</p>

<p>
  <strong>Curator:</strong>
  <%= @resume.curator %>
</p>

<p>
  <strong>Link:</strong>
  <%= @resume.link %>
</p>
<br>
<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>
</div>